<!-- Transportation sql -->
<!ENTITY sql-ferry-routes SYSTEM "ferry-routes.sql">
<!ENTITY sql-pedestrian-walkways SYSTEM "pedestrian-walkways.sql">
<!ENTITY sql-cycleway SYSTEM "cycleway.sql">
<!ENTITY sql-alley SYSTEM "alley.sql">
<!ENTITY sql-ramp SYSTEM "ramp.sql">
<!ENTITY sql-street4 SYSTEM "street4.sql">
<!ENTITY sql-street3 SYSTEM "street3.sql">
<!ENTITY sql-street2 SYSTEM "street2.sql">
<!ENTITY sql-street1 SYSTEM "street1.sql">
<!ENTITY sql-street1-toll SYSTEM "street1-toll.sql">
<!ENTITY sql-pedestrian-polygon SYSTEM "pedestrian-polygon.sql">
<!ENTITY sql-runway SYSTEM "runway.sql">
<!ENTITY sql-rail SYSTEM "rail.sql">
<!ENTITY sql-alley SYSTEM "alley.sql">
<!ENTITY sql-shield-us SYSTEM "shield-us.sql">

