<!ENTITY layer-streetnames SYSTEM "layer-streetnames-eu.xml.inc">
<!ENTITY layer-text SYSTEM "layer-text.xml.inc">
<!ENTITY layer-amenity-symbols SYSTEM "layer-symbols.xml.inc">
<!ENTITY layer-border SYSTEM "layer-border-eu-uk.xml.inc">


<!ENTITY layer-transportation SYSTEM "layer-transportation-eu.xml.inc">

                                                           
<!ENTITY layer-base SYSTEM "layer-base.xml.inc">