<!ENTITY layer-streetnames SYSTEM "layer-streetnames-us.xml.inc">
<!ENTITY layer-text SYSTEM "layer-text.xml.inc">
<!ENTITY layer-symbols SYSTEM "layer-symbols.xml.inc">
<!ENTITY layer-border SYSTEM "layer-border-us.xml.inc">
<!ENTITY layer-border-casing SYSTEM "layer-border-casing-us.xml.inc">
<!ENTITY layer-transportation SYSTEM "layer-transportation-us.xml.inc">
<!ENTITY layer-transportation-common-cycleway SYSTEM "layer-transportation-common-cycleway.xml.inc">
<!ENTITY layer-base SYSTEM "layer-base.xml.inc">